### ISSUE TITLE
Needs an update!

### ISSUE THREAD

**Issue by siffegh** [rotemdan/NoFocusOutlines#1]
Works on some things, others not.

**Comment by rotemdan** [comment]
Here's the entire source code of the extension. It's a CSS file:

```css
:focus {
	outline: none !important;
}

::-moz-focus-inner {
	border: 0 !important;
}

select:-moz-focusring {
    color: transparent !important;
    text-shadow: 0 0 0 #000 !important;
}
```

It works on native HTML focus outlines. Maybe the kind you're referring to is produced by a [library like bootstrap](https://getbootstrap.com/docs/4.0/components/buttons/)? (see the focus outlines on the demo buttons). In that case the extension will not handle it, because it is not native to the browser and changes between different libraries and library versions.
